# Generated by Django 4.1.3 on 2023-03-05 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True)),
                ('classe', models.CharField(choices=[('ações', 'Ações_BR'), ('fiis', 'Fundos Imobiliários'), ('stocks', 'Stocks'), ('reits', 'Reits americanos'), ('Cryptos', 'Criptoativos'), ('etfs', 'ETF BR'), ('etf_us', 'ETF US'), ('caixa', 'Caixa')], default='caixa', max_length=10)),
                ('nome', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=10)),
                ('pm_un', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
