# Generated by Django 4.1.3 on 2023-03-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='custo_total',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='max_pago',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='min_pago',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
    ]
