# Generated by Django 4.1.3 on 2023-03-10 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True)),
                ('patrimonio', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ativo',
            name='total_atual',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='total_atual_usd',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='classe',
            field=models.CharField(choices=[('ações', 'Ações_BR'), ('fiis', 'Fundos Imobiliários'), ('stocks', 'Stocks'), ('reits', 'Reits americanos'), ('Cryptos', 'Criptoativos'), ('etfs_br', 'ETF BR'), ('etf_us', 'ETF US'), ('caixa', 'Caixa')], default='caixa', max_length=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='de_dividendos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
