# Generated by Django 4.1.3 on 2023-03-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_patrimonio_ativo_total_atual_ativo_total_atual_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='lucro_preju',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
    ]
