# Generated by Django 4.1.3 on 2023-03-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_ativo_lucro_preju'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='lucro_preju_usd',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='perc_grupo',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
    ]
