# Generated by Django 4.1.3 on 2023-03-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0006_ativo_lucro_preju_usd_ativo_perc_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='un_atual_brl',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='pm_un',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
    ]
