# Generated by Django 4.1.3 on 2023-03-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0007_ativo_un_atual_alter_ativo_pm_un_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='perc_total',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
    ]
