# Generated by Django 4.1.3 on 2023-03-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0008_ativo_perc_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='perc_lucro',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='perc_grupo',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='perc_total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
