# Generated by Django 4.1.3 on 2023-03-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0009_ativo_perc_lucro_alter_ativo_perc_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='classe',
            field=models.CharField(choices=[('ações', 'Ações_BR'), ('fiis', 'Fundos Imobiliários'), ('stocks', 'Stocks'), ('reits', 'Reits americanos'), ('cryptos', 'Criptoativos'), ('etfs_br', 'ETF BR'), ('etf_us', 'ETF US'), ('caixa', 'Caixa')], default='caixa', max_length=10),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='custo_total',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='lucro_preju',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='lucro_preju_usd',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='max_pago',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='min_pago',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='perc_grupo',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='perc_lucro',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='perc_total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='pm_un',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='total_atual',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='total_atual_usd',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='un_atual_brl',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cotacao_ent_brl',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cotacao_ent_usd',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cotacao_sai_brl',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cotacao_sai_usd',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='custo_total',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='registro',
            name='qtd_entrada',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='registro',
            name='taxa',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='total_entrada_brl',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='total_entrada_usd',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='total_saida_brl',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='total_saida_usd',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
    ]
