# Generated by Django 4.1.3 on 2023-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0010_alter_ativo_classe_alter_ativo_custo_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='un_atual_usd',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True),
        ),
    ]
