# Generated by Django 4.1.3 on 2023-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0013_alter_ativo_custo_total_alter_ativo_lucro_preju_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='lucro_preju',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='lucro_preju_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='max_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='min_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='perc_grupo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='perc_lucro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='perc_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='pm_un',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='total_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='total_atual_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='un_atual_brl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='un_atual_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cotacao_ent_brl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cotacao_ent_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cotacao_sai_brl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cotacao_sai_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='custo_total',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='registro',
            name='qtd_entrada',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='registro',
            name='total_entrada_brl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='total_entrada_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='total_saida_brl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='total_saida_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
    ]
