# Generated by Django 4.1.3 on 2023-04-12 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True)),
                ('classe', models.CharField(choices=[('ações', 'Ações_BR'), ('fiis', 'Fundos Imobiliários'), ('stocks', 'Stocks'), ('reits', 'Reits americanos'), ('cryptos', 'Criptoativos'), ('etfs_br', 'ETF BR'), ('etf_us', 'ETF US'), ('caixa', 'Caixa')], default='caixa', max_length=10)),
                ('nome', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=6, default=None, max_digits=14, null=True)),
                ('pm_un', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('min_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('max_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_atual_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('perc_grupo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('un_atual_brl', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('un_atual_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('perc_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('lucro_preju', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('lucro_preju_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('perc_lucro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True)),
                ('patrimonio', models.FloatField(blank=True, default=0, null=True)),
                ('patrimonio_usd', models.FloatField(blank=True, default=0, null=True)),
                ('classes_percent', models.JSONField(blank=True, default=dict)),
                ('classes_values', models.JSONField(blank=True, default=dict)),
                ('assets_percent', models.JSONField(blank=True, default=dict)),
                ('assets_values', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('moeda_utilizada', models.CharField(max_length=10)),
                ('custo_total', models.DecimalField(decimal_places=6, default=0.0, max_digits=14)),
                ('total_saida_brl', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('cotacao_sai_brl', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('total_saida_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('cotacao_sai_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('ativo_adquirido', models.CharField(max_length=10)),
                ('qtd_entrada', models.DecimalField(decimal_places=6, default=0.0, max_digits=14)),
                ('total_entrada_brl', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('cotacao_ent_brl', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('total_entrada_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('cotacao_ent_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('taxa', models.DecimalField(decimal_places=6, default=0, max_digits=14, null=True)),
                ('cambio_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('de_dividendos', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
